export enum StorageKeys {
  ACCESS_TOKEN_KEY = 'ACCESS_TOKEN_KEY',
  REFRESH_TOKEN_KEY = 'REFRESH_TOKEN_KEY',
  ID_TOKEN_KEY = 'ID_TOKEN_KEY',
  KEYCLOAK_ID = 'KEYCLOAK_ID',
  EXPIRES_AT_KEY = 'EXPIRES_AT_KEY',
}
